name: preserve-staging.yml
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  build:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'staging'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email 'actions@github.com'
          git config --global user.name 'GitHub Actions'

      - name: Create staging branch
        run: |
          git checkout main
          git pull origin main
          git branch -f staging
          git push -f origin staging
        env:
            GH_PAT: ${{ secrets.GH_PAT }}
